services:
  # frontend:
  #   build: ./frontend
  #   container_name: frontend-image
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network

  backend:
    build: ./backend
    container_name: backend-image
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://cs348:group10@db:5432/housing_db
      - PYTHONPATH=/backend
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: cs348
      POSTGRES_PASSWORD: group10
      POSTGRES_DB: housing_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
  
