FROM postgres:17

USER root

RUN apt-get update \
 && apt-get install -y wget gnupg \
 && wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
 && echo "deb http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" \
      > /etc/apt/sources.list.d/pgdg.list

RUN apt-get update \
 && apt-get install -y \ 
      postgresql-17-cron \
      postgresql-17-postgis-3 \
      postgresql-17-postgis-3-scripts \ 
 && rm -rf /var/lib/apt/lists/*

CMD ["postgres", "-c", "shared_preload_libraries=pg_cron", "-c", "cron.database_name=housing_db"]

