FROM postgres:17

USER root

RUN apt-get update \
 && apt-get install -y wget gnupg \
 && wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
 && echo "deb http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" \
      > /etc/apt/sources.list.d/pgdg.list

RUN apt-get update \
 && apt-get install -y postgresql-17-cron \
 && rm -rf /var/lib/apt/lists/*

RUN echo "shared_preload_libraries = 'pg_cron'" \
      >> "$PGDATA"/postgresql.conf
